#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
/home/$USER/.config/bspwm/autostart.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

bspc config border_width    2
bspc config window_gap      8

bspc config split_ratio             0.50
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   false

# Padding Rule
# bspc config top_padding 27

# Colors
#bspc config normal_border_color "#44475a"
#bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#819A67"
#bspc config presel_feedback_color "#6272a4"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Firefox-esr desktop='^2'
bspc rule -a Pcmanfm desktop='^3'
bspc rule -a Evince desktop='^4'
bspc rule -a Transmission-gtk desktop='^5'
bspc rule -a MEGAsync state=floating border=off follow=off

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# bspc rule -a Nitrogen state=floating

# Cursor
 xsetroot -cursor_name left_ptr &

 # Disable screen going black
 xset -dpms &
 xset s off &
