
[greenclip]
  blacklisted_applications = []
  enable_image_support = true
  history_file = "/home/$USER/.cache/greenclip.history"
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 30
  max_selection_size_bytes = 0
  static_history = ["Use ARROW keys to move and ENTER to copy the selection."]
  trim_space_from_selection = true
  use_primary_selection_as_input = false
